# Generated by Django 4.2.4 on 2023-09-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='uploads/legacy/agPolo')),
            ],
        ),
    ]
