# Generated by Django 4.2.4 on 2023-09-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grad',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
