# Generated by Django 4.2.4 on 2023-09-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legacy', '0002_grad_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('type_of_team', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tournament', models.CharField(blank=True, max_length=255, null=True)),
                ('placement', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
