# Generated by Django 4.2.4 on 2023-09-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legacy', '0003_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='agPolo_Record',
        ),
    ]
