# Generated by Django 4.2.4 on 2023-09-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legacy', '0004_rename_record_agpolo_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agPolo_Record',
        ),
    ]
