# Generated by Django 4.2.4 on 2023-09-18 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Legacy', '0006_ag_polo_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeTeam',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='agPolo_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_team', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament', models.CharField(blank=True, max_length=255, null=True)),
                ('placement', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('age_of_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Legacy.ageteam')),
            ],
        ),
        migrations.DeleteModel(
            name='ag_polo_record',
        ),
    ]
