# Generated by Django 5.1.5 on 2025-01-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0003_remove_program_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/summerProgram'),
        ),
    ]
