# Generated by Django 5.1.5 on 2025-01-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0004_program_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('recswim_info', models.TextField(blank=True, null=True)),
                ('weekdays', models.CharField(blank=True, max_length=255, null=True)),
                ('weekdays_timeframe', models.CharField(blank=True, max_length=255, null=True)),
                ('weekends', models.CharField(blank=True, max_length=255, null=True)),
                ('weekends_timeframe', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('registration_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
