# Generated by Django 5.1.5 on 2025-01-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0005_pageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/summerProgram'),
        ),
    ]
