# Generated by Django 5.1.5 on 2025-01-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0006_pageinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/summerProgram', verbose_name='Recswim image'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='weekdays',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weekdays for Recswim'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='weekends',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weekends for Recswim'),
        ),
    ]
