# Generated by Django 5.1.5 on 2025-01-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0007_alter_pageinfo_image_alter_pageinfo_weekdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='weekdays',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weekdays Schedule for Recswim'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='weekends',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weekends Schedule for Recswim'),
        ),
    ]
