# Generated by Django 5.1.5 on 2025-01-29 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0008_alter_pageinfo_weekdays_alter_pageinfo_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='number_of_weekend_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WeekendSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekend_sessions', to='summProgram.program')),
            ],
        ),
    ]
