# Generated by Django 5.1.5 on 2025-02-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0009_program_number_of_weekend_sessions_weekendsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='class_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='fee_note',
            field=models.TextField(blank=True, null=True, verbose_name='Program Notes'),
        ),
    ]
