# Generated by Django 5.1.5 on 2025-02-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0010_program_class_duration_alter_program_fee_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='class_duration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
