# Generated by Django 5.1.5 on 2025-02-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summProgram', '0011_alter_program_class_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='weekend_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weekday Fee'),
        ),
    ]
