# Generated by Django 4.2.4 on 2023-09-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutusEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('AD_name', models.CharField(blank=True, max_length=255, null=True)),
                ('AD_desc', models.TextField(blank=True, null=True)),
                ('PC_name', models.CharField(blank=True, max_length=255, null=True)),
                ('PC_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
