# Generated by Django 4.2.4 on 2023-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusedit',
            name='AD_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/aboutus'),
        ),
        migrations.AddField(
            model_name='aboutusedit',
            name='PC_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/aboutus'),
        ),
    ]
