# Generated by Django 4.2.4 on 2023-10-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_aboutusedit_ad_pic_aboutusedit_pc_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusedit',
            name='AD_pic',
            field=models.ImageField(upload_to='uploads/aboutus'),
        ),
        migrations.AlterField(
            model_name='aboutusedit',
            name='PC_pic',
            field=models.ImageField(upload_to='uploads/aboutus'),
        ),
    ]
