# Generated by Django 4.2.4 on 2024-05-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_alter_aboutusedit_ad_pic_alter_aboutusedit_pc_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Job')),
                ('jobDesc_file', models.FileField(upload_to='uploads/coachesEmail/agSwim', verbose_name='Dscription of Job')),
            ],
        ),
    ]
