# Generated by Django 4.2.4 on 2024-05-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_jobdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdesc',
            name='jobDesc_file',
            field=models.FileField(upload_to='uploads/aboutus/jobDesc', verbose_name='Dscription of Job'),
        ),
    ]
