# Generated by Django 4.2.4 on 2025-01-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_download_link',
            field=models.BooleanField(default=False, help_text='Toggle to show or hide the download link for Summer Swim Lessons.', verbose_name='Display Summer Lesson Info'),
        ),
    ]
