# Generated by Django 4.2.4 on 2025-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_homepage_show_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='show_download_link',
            field=models.BooleanField(default=False, help_text='Click box to display Summer Swim Lesson', verbose_name='Display Summer Lesson Info'),
        ),
    ]
