# Generated by Django 5.1.5 on 2025-02-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_homepage_show_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='popUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('display_status', models.BooleanField(default=False)),
                ('downloadable_file', models.FileField(upload_to='uploads/Home/popup')),
                ('file_status', models.BooleanField(default=False)),
            ],
        ),
    ]
