# Generated by Django 5.1.5 on 2025-02-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='downloadable_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Home/popup'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
