# Generated by Django 5.1.5 on 2025-02-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_popup_downloadable_file_alter_popup_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='show_download_link',
            field=models.BooleanField(default=False, help_text='Click box to display Summer Swim Lesson', verbose_name='Display Summer Program Info'),
        ),
    ]
