# Generated by Django 5.1.5 on 2025-02-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_popup_display_status_alter_popup_file_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='popUp',
        ),
    ]
