# Generated by Django 5.1.5 on 2025-02-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_delete_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='show_download_link',
            field=models.BooleanField(default=False, verbose_name='Display Summer Program Info'),
        ),
    ]
