# Generated by Django 4.2.5 on 2023-09-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='uploads/coaches/masterPolo')),
            ],
        ),
        migrations.CreateModel(
            name='compCoachPolo',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='uploads/coaches/agPolo')),
            ],
        ),
        migrations.CreateModel(
            name='compCoachSwim',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='uploads/coaches/agSwim')),
            ],
        ),
        migrations.CreateModel(
            name='mCoachSwim',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='uploads/coaches/mastersSwim')),
            ],
        ),
    ]
