# Generated by Django 4.2.4 on 2023-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compcoachswim',
            name='coaches_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
