# Generated by Django 4.2.5 on 2023-09-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('weekdays_morning', models.CharField(blank=True, max_length=255, null=True)),
                ('weekdays_afternoon', models.CharField(blank=True, max_length=255, null=True)),
                ('weekdays_evening', models.CharField(blank=True, max_length=255, null=True)),
                ('weekends', models.CharField(blank=True, max_length=255, null=True)),
                ('shortCourse_occur', models.CharField(blank=True, max_length=255, null=True)),
                ('longCourse_occur', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quarterly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
