# Generated by Django 4.2.5 on 2023-09-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGpoloEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='uploads/coachesEmail/agPolo')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGpoloPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('new_members_description', models.TextField(blank=True, null=True)),
                ('records_description', models.TextField(blank=True, null=True)),
                ('alumni_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGswimEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='uploads/coachesEmail/agSwim')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGswimPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('urgent', models.TextField(blank=True, null=True)),
                ('description_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('practice_info_header', models.CharField(blank=True, max_length=255, null=True)),
                ('practice_group_box_name', models.CharField(blank=True, max_length=255, null=True)),
                ('practice_schedule_box_name', models.CharField(blank=True, max_length=255, null=True)),
                ('swim_meet_header', models.CharField(blank=True, max_length=255, null=True)),
                ('swim_meet_box_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_members_title', models.CharField(blank=True, max_length=255, null=True)),
                ('new_members_description', models.TextField(blank=True, null=True)),
                ('current_members_title', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_title', models.CharField(blank=True, max_length=255, null=True)),
                ('records_description', models.TextField(blank=True, null=True)),
                ('alumni_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
