# Generated by Django 4.2.4 on 2023-10-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competitive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agpolopage',
            name='polo_registration',
            field=models.URLField(blank=True, null=True),
        ),
    ]
