# Generated by Django 4.2.4 on 2023-10-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Competitive', '0002_agpolopage_polo_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agpolopage',
            old_name='polo_registration',
            new_name='polo_registration_link',
        ),
    ]
