# Generated by Django 5.1.5 on 2025-01-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('adjusted', 'Adjusted Schedule'), ('closed', 'Closed')], max_length=20)),
                ('scheduled_time', models.CharField(max_length=50)),
            ],
        ),
    ]
