# Generated by Django 5.1.5 on 2025-01-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='number_of_holidays',
            field=models.IntegerField(default=1),
        ),
    ]
