# Generated by Django 5.1.5 on 2025-01-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_holiday_number_of_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='scheduled_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
