# Generated by Django 5.1.5 on 2025-01-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_alter_holiday_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='number_of_holidays',
        ),
    ]
