# Generated by Django 5.1.5 on 2025-01-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0004_remove_holiday_number_of_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='status',
            field=models.CharField(choices=[('adjusted', 'Adjusted Schedule'), ('closed', 'Closed'), ('regular', 'Regular Schedule')], max_length=20),
        ),
    ]
