# Generated by Django 4.2.4 on 2023-09-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('lesson_rate', models.TextField(blank=True, null=True)),
                ('lesson_length', models.TextField(blank=True, null=True)),
                ('swimmer_to_instructor_ratio', models.TextField(blank=True, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('registration_info', models.TextField(blank=True, null=True)),
                ('waitlist_info', models.TextField(blank=True, null=True)),
                ('policy', models.TextField(blank=True, null=True)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
