# Generated by Django 4.2.4 on 2023-09-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='swimmer_to_instructor_ratio',
            new_name='baracuda',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='daily_fee',
        ),
        migrations.AddField(
            model_name='schedule',
            name='preschool',
            field=models.TextField(blank=True, null=True),
        ),
    ]
