# Generated by Django 4.2.4 on 2023-09-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0002_rename_swimmer_to_instructor_ratio_schedule_baracuda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='info',
        ),
    ]
