# Generated by Django 4.2.4 on 2023-09-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0003_remove_schedule_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='baracuda',
            new_name='barracuda',
        ),
    ]
