# Generated by Django 4.2.4 on 2023-09-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0004_rename_baracuda_schedule_barracuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('parent_and_me_description', models.TextField(blank=True, null=True)),
                ('parent_and_me_age', models.TextField(blank=True, null=True)),
                ('preschool1_description', models.TextField(blank=True, null=True)),
                ('preschool1_age', models.TextField(blank=True, null=True)),
                ('preschool2_description', models.TextField(blank=True, null=True)),
                ('preschool2_age', models.TextField(blank=True, null=True)),
                ('barracuda1_description', models.TextField(blank=True, null=True)),
                ('barracuda1_age', models.TextField(blank=True, null=True)),
                ('barracuda2_description', models.TextField(blank=True, null=True)),
                ('barracuda2_age', models.TextField(blank=True, null=True)),
                ('barracuda3_description', models.TextField(blank=True, null=True)),
                ('barracuda3_age', models.TextField(blank=True, null=True)),
                ('barracuda4_age', models.TextField(blank=True, null=True)),
                ('barracuda4_description', models.TextField(blank=True, null=True)),
                ('preteam_description', models.TextField(blank=True, null=True)),
                ('preteam_age', models.TextField(blank=True, null=True)),
                ('gators_description', models.TextField(blank=True, null=True)),
                ('gators_age', models.TextField(blank=True, null=True)),
                ('adult_lessons_description', models.TextField(blank=True, null=True)),
                ('registration_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
