# Generated by Django 4.2.4 on 2023-09-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0005_groupdetailschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetailschedule',
            name='preschool3_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='preschool3_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
