# Generated by Django 4.2.4 on 2023-09-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0006_groupdetailschedule_preschool3_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='parent_and_me_age',
            new_name='small_pool_five_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='parent_and_me_description',
            new_name='small_pool_five_description',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preschool1_age',
            new_name='small_pool_four_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preschool1_description',
            new_name='small_pool_four_description',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preschool2_age',
            new_name='small_pool_one_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preschool2_description',
            new_name='small_pool_one_description',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preschool3_age',
            new_name='small_pool_six_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preschool3_description',
            new_name='small_pool_six_description',
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_three_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_three_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_two_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_two_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
