# Generated by Django 4.2.4 on 2023-09-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0007_rename_parent_and_me_age_groupdetailschedule_small_pool_five_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_five_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_four_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_one_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_six_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_three_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_two_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
