# Generated by Django 4.2.4 on 2023-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0008_groupdetailschedule_small_pool_five_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='adult_lessons_description',
            new_name='big_pool_eight_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda1_age',
            new_name='big_pool_eight_description',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda1_description',
            new_name='big_pool_eight_name',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda2_age',
            new_name='big_pool_five_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda2_description',
            new_name='big_pool_five_description',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda3_age',
            new_name='big_pool_five_name',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda3_description',
            new_name='big_pool_four_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda4_age',
            new_name='big_pool_four_description',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='barracuda4_description',
            new_name='big_pool_four_name',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='gators_age',
            new_name='big_pool_one_age',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='gators_description',
            new_name='big_pool_one_description',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preteam_age',
            new_name='big_pool_one_name',
        ),
        migrations.RenameField(
            model_name='groupdetailschedule',
            old_name='preteam_description',
            new_name='big_pool_seven_age',
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_seven_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_seven_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_six_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_six_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_six_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_three_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_three_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_three_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_two_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_two_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_two_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
