# Generated by Django 4.2.4 on 2023-09-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0009_rename_adult_lessons_description_groupdetailschedule_big_pool_eight_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('lesson1_name', models.TextField(blank=True, null=True)),
                ('lesson1_age', models.TextField(blank=True, null=True)),
                ('lesson1_description', models.TextField(blank=True, null=True)),
                ('lesson2_name', models.TextField(blank=True, null=True)),
                ('lesson2_age', models.TextField(blank=True, null=True)),
                ('lesson2_description', models.TextField(blank=True, null=True)),
                ('philosophy_heading', models.TextField(blank=True, null=True)),
                ('philosophy_info', models.TextField(blank=True, null=True)),
                ('policy_heading', models.TextField(blank=True, null=True)),
                ('policy_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
