# Generated by Django 4.2 on 2023-09-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0011_remove_groupdetailschedule_big_pool_eight_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_eight_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_eight_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_eight_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_five_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_five_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_five_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_four_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_four_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_four_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_one_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_one_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_one_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_seven_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_seven_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_seven_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_six_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_six_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_six_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_three_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_three_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_three_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_two_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_two_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='big_pool_two_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_five_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_five_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_five_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_four_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_four_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_four_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_one_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_one_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_one_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_six_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_six_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_six_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_three_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_three_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_three_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_two_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_two_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdetailschedule',
            name='small_pool_two_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
