# Generated by Django 4.2 on 2023-09-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0012_groupdetailschedule_big_pool_eight_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_eight_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_eight_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_five_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_five_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_four_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_four_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_one_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_one_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_seven_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_seven_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_six_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_six_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_three_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_three_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_two_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='big_pool_two_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_five_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_five_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_four_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_four_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_one_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_one_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_six_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_six_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_three_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_three_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_two_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdetailschedule',
            name='small_pool_two_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
