# Generated by Django 4.2.4 on 2023-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0013_alter_groupdetailschedule_big_pool_eight_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='barracuda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='preschool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
