# Generated by Django 4.2.4 on 2023-09-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0014_alter_schedule_barracuda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateschedule',
            name='lesson1_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privateschedule',
            name='lesson1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privateschedule',
            name='lesson2_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privateschedule',
            name='lesson2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privateschedule',
            name='philosophy_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privateschedule',
            name='policy_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
