# Generated by Django 4.2.4 on 2024-02-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0016_privateschedule_registraion_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('lesson_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_length', models.CharField(blank=True, max_length=255, null=True)),
                ('preschool', models.CharField(blank=True, max_length=255, null=True)),
                ('barracuda', models.CharField(blank=True, max_length=255, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('registration_info', models.TextField(blank=True, null=True)),
                ('waitlist_info', models.TextField(blank=True, null=True)),
                ('policy', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
