# Generated by Django 4.2.4 on 2024-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0017_swimlessons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='swimlessons',
            name='policy',
            field=models.TextField(blank=True, help_text='Enter bullet points separated by line breaks.', null=True),
        ),
        migrations.AlterField(
            model_name='swimlessons',
            name='registration_info',
            field=models.TextField(blank=True, help_text='Enter bullet points separated by line breaks.', null=True),
        ),
        migrations.AlterField(
            model_name='swimlessons',
            name='waitlist_info',
            field=models.TextField(blank=True, help_text='Enter bullet points separated by line breaks.', null=True),
        ),
    ]
