# Generated by Django 4.2.4 on 2024-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0018_delete_schedule_alter_swimlessons_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimlessons',
            name='policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimlessons',
            name='registration_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimlessons',
            name='waitlist_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
