# Generated by Django 4.2.4 on 2024-02-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0019_alter_swimlessons_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimlessons',
            name='registration_info',
            field=models.TextField(blank=True, help_text='Separate point by making a new line (hit enter)', null=True),
        ),
    ]
