# Generated by Django 4.2.4 on 2024-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0020_alter_swimlessons_registration_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimlessons',
            name='policy',
            field=models.TextField(blank=True, help_text='Separate point by making a new line (hit enter)', null=True),
        ),
        migrations.AlterField(
            model_name='swimlessons',
            name='waitlist_info',
            field=models.TextField(blank=True, help_text='Separate point by making a new line (hit enter)', null=True),
        ),
    ]
