# Generated by Django 4.2.4 on 2024-02-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0022_swim_lessons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwimLessons',
        ),
    ]
