# Generated by Django 4.2.4 on 2024-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0023_delete_swimlessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('registration_info', models.TextField(blank=True, help_text='Separate point by making a new line (hit enter)', null=True)),
                ('waitlist_info', models.TextField(blank=True, help_text='Separate point by making a new line (hit enter)', null=True)),
                ('policy', models.TextField(blank=True, help_text='Separate point by making a new line (hit enter)', null=True)),
                ('display_roadmap', models.BooleanField(default=False, help_text='Check this to display the roadmap on the website')),
                ('roadmap_image', models.ImageField(blank=True, help_text='Upload a roadmap image', null=True, upload_to='uploads/lesson/frontPage')),
            ],
        ),
    ]
