# Generated by Django 4.2.4 on 2024-02-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0024_swimlessons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Swim_Lessons',
        ),
    ]
