# Generated by Django 4.2.4 on 2024-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0025_delete_swim_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessonInfoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('location_of_beginner_lesson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_of_advanced_lesson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
