# Generated by Django 4.2.4 on 2024-02-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0026_lessoninfohome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessoninfohome',
            old_name='location_of_advanced_lesson_name',
            new_name='location_of_advanced_lessons',
        ),
        migrations.RenameField(
            model_name='lessoninfohome',
            old_name='location_of_beginner_lesson_name',
            new_name='location_of_beginner_lessons',
        ),
    ]
