# Generated by Django 4.2.4 on 2024-02-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0027_rename_location_of_advanced_lesson_name_lessoninfohome_location_of_advanced_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of group')),
                ('location', models.CharField(choices=[('SP', 'Small Pool'), ('BP', 'Big Pool')], default='SP', max_length=2, verbose_name='Location of Lesson')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Level')),
                ('instructor_swimmer_ratio', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Instructor/Swimmer ratio')),
                ('benchmark1', models.TextField(verbose_name='Benchmark 1')),
                ('picture1', models.ImageField(upload_to='uploads/lesson/lessonInfo', verbose_name='Picture for Benchmark 1')),
                ('benchmark2', models.TextField(verbose_name='Benchmark 2')),
                ('picture2', models.ImageField(upload_to='uploads/lesson/lessonInfo/', verbose_name='Picture for Benchmark 2')),
                ('benchmark3', models.TextField(verbose_name='Benchmark 3')),
                ('picture3', models.ImageField(upload_to='uploads/lesson/lessonInfo/', verbose_name='Picture for Benchmark 3')),
            ],
        ),
    ]
