# Generated by Django 4.2.4 on 2024-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0028_groupdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetail',
            name='benchmark1',
            field=models.TextField(blank=True, null=True, verbose_name='Benchmark 1'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='benchmark2',
            field=models.TextField(blank=True, null=True, verbose_name='Benchmark 2'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='benchmark3',
            field=models.TextField(blank=True, null=True, verbose_name='Benchmark 3'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='instructor_swimmer_ratio',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, null=True, verbose_name='Instructor/Swimmer ratio'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='location',
            field=models.CharField(blank=True, choices=[('SP', 'Small Pool'), ('BP', 'Big Pool')], default='SP', max_length=2, null=True, verbose_name='Location of Lesson'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of group'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo', verbose_name='Picture for Benchmark 1'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo/', verbose_name='Picture for Benchmark 2'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo/', verbose_name='Picture for Benchmark 3'),
        ),
    ]
