# Generated by Django 4.2.4 on 2024-02-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0029_alter_groupdetail_benchmark1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupDetail',
            new_name='Group_Lesson_Info',
        ),
    ]
