# Generated by Django 4.2.4 on 2024-02-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0030_rename_groupdetail_group_lesson_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_lesson_info',
            name='location',
        ),
        migrations.RemoveField(
            model_name='group_lesson_info',
            name='picture2',
        ),
        migrations.AddField(
            model_name='group_lesson_info',
            name='benchmark1_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Benchmark 1'),
        ),
        migrations.AddField(
            model_name='group_lesson_info',
            name='benchmark2_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Benchmark 2'),
        ),
        migrations.AddField(
            model_name='group_lesson_info',
            name='benchmark3_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Benchmark 3'),
        ),
        migrations.AddField(
            model_name='group_lesson_info',
            name='benchmark4',
            field=models.TextField(blank=True, null=True, verbose_name='Benchmark 4 Description'),
        ),
        migrations.AddField(
            model_name='group_lesson_info',
            name='benchmark4_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Benchmark 4'),
        ),
        migrations.AddField(
            model_name='group_lesson_info',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo', verbose_name='Picture for Benchmark 4'),
        ),
        migrations.AlterField(
            model_name='group_lesson_info',
            name='benchmark1',
            field=models.TextField(blank=True, null=True, verbose_name='Benchmark 1 Description'),
        ),
        migrations.AlterField(
            model_name='group_lesson_info',
            name='benchmark2',
            field=models.TextField(blank=True, null=True, verbose_name='Benchmark 2 Description'),
        ),
        migrations.AlterField(
            model_name='group_lesson_info',
            name='benchmark3',
            field=models.TextField(blank=True, null=True, verbose_name='Benchmark 3 Description'),
        ),
        migrations.AlterField(
            model_name='group_lesson_info',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo', verbose_name='Picture for Benchmark 2'),
        ),
        migrations.AlterField(
            model_name='group_lesson_info',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo', verbose_name='Picture for Benchmark 3'),
        ),
    ]
