# Generated by Django 4.2.4 on 2024-02-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0031_remove_group_lesson_info_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_lesson_info',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo', verbose_name='Picture for Benchmark 2'),
        ),
        migrations.AlterField(
            model_name='group_lesson_info',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson/lessonInfo', verbose_name='Picture for Benchmark 1'),
        ),
    ]
