# Generated by Django 4.2.4 on 2024-02-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0032_group_lesson_info_picture2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_lesson_info',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Group Description'),
        ),
    ]
