# Generated by Django 4.2.4 on 2024-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0034_remove_lessoninfohome_location_of_advanced_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_lesson_info',
            name='ages',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ages for lessons'),
        ),
    ]
