# Generated by Django 4.2.4 on 2024-03-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0036_alter_group_lesson_info_instructor_swimmer_ratio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupDetailSchedule',
        ),
    ]
