# Generated by Django 4.2.5 on 2023-09-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('schedule_notes', models.TextField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=255, null=True)),
                ('weekdays_timeframe', models.CharField(blank=True, max_length=255, null=True)),
                ('weekends', models.CharField(blank=True, max_length=255, null=True)),
                ('weekends_timeframe', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('practiceNotes_one', models.TextField(blank=True, null=True)),
                ('practiceNotes_two', models.TextField(blank=True, null=True)),
                ('practiceNotes_three', models.TextField(blank=True, null=True)),
                ('practiceNotes_four', models.TextField(blank=True, null=True)),
                ('registration', models.TextField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSwim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.TextField(blank=True, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('weekdays_morning', models.CharField(blank=True, max_length=255, null=True)),
                ('weekdays_afternoon', models.CharField(blank=True, max_length=255, null=True)),
                ('weekends', models.CharField(blank=True, max_length=255, null=True)),
                ('shortCourse_morning_practices', models.CharField(blank=True, max_length=255, null=True)),
                ('shortCourse_afternoon_practices', models.CharField(blank=True, max_length=255, null=True)),
                ('shortCourse_weekend_pracitces', models.CharField(blank=True, max_length=255, null=True)),
                ('longCourse_morning_pracitces', models.CharField(blank=True, max_length=255, null=True)),
                ('longCourse_weekend_pracitces', models.CharField(blank=True, max_length=255, null=True)),
                ('registration', models.TextField(blank=True, null=True)),
                ('quarterly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
