# Generated by Django 4.2.4 on 2024-02-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleswim',
            old_name='quarterly_fee',
            new_name='ticket_pass',
        ),
    ]
