# Generated by Django 4.2.4 on 2024-03-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0002_rename_quarterly_fee_scheduleswim_ticket_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepolo',
            name='monthly_fee',
        ),
        migrations.AddField(
            model_name='schedulepolo',
            name='blue_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Blue Team Fee'),
        ),
        migrations.AddField(
            model_name='schedulepolo',
            name='gold_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gold Team Fee'),
        ),
        migrations.AddField(
            model_name='schedulepolo',
            name='ticket_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='10-pack Fee'),
        ),
        migrations.AlterField(
            model_name='schedulepolo',
            name='daily_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Drop-in Fee'),
        ),
    ]
