# Generated by Django 4.2.4 on 2024-05-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0003_remove_schedulepolo_monthly_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleswim',
            old_name='shortCourse_weekend_pracitces',
            new_name='shortCourse_weekend_practices',
        ),
    ]
