# Generated by Django 4.2.4 on 2024-07-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0004_rename_shortcourse_weekend_pracitces_scheduleswim_shortcourse_weekend_practices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleswim',
            name='longCourse_morning_pracitces',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='longCourse_weekend_pracitces',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='shortCourse_afternoon_practices',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='shortCourse_morning_practices',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='shortCourse_weekend_practices',
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='LC_morning_pracitces',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Long Course Morning Practice'),
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='LC_weekend_pracitces',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Long Course Weekend Practice'),
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='SC_afternoon_practices',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Course Afternoon Practice'),
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='SC_morning_practices',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Course Morning Practice'),
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='SC_weekend_practices',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Course Weekend Practice'),
        ),
    ]
