# Generated by Django 4.2.4 on 2024-07-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0005_remove_scheduleswim_longcourse_morning_pracitces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleswim',
            name='specEVent_registration_link',
            field=models.URLField(blank=True, null=True, verbose_name='Special Event Link'),
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='specEvent_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Special Event Description'),
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='specEvent_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Special Event Title'),
        ),
    ]
