# Generated by Django 4.2.4 on 2024-07-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0006_scheduleswim_specevent_registration_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleswim',
            name='specEvent_button_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Button Link'),
        ),
    ]
