# Generated by Django 4.2.4 on 2024-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0007_scheduleswim_specevent_button_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleswim',
            name='specEvent_display',
            field=models.BooleanField(default=False, help_text='Check this to display Special Events on the website'),
        ),
    ]
