# Generated by Django 4.2.4 on 2024-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0008_scheduleswim_specevent_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleswim',
            name='newsletterDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of recent update'),
        ),
        migrations.AddField(
            model_name='scheduleswim',
            name='newsletterLink',
            field=models.URLField(blank=True, null=True, verbose_name='Newsletter Link'),
        ),
    ]
