# Generated by Django 4.2.4 on 2024-08-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0009_scheduleswim_newsletterdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleswim',
            name='newsletterDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of Newsletter Update'),
        ),
    ]
