# Generated by Django 5.1.5 on 2025-01-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MastersBAC', '0010_alter_scheduleswim_newsletterdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleswim',
            name='LC_morning_pracitces',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='LC_weekend_pracitces',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='SC_afternoon_practices',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='SC_morning_practices',
        ),
        migrations.RemoveField(
            model_name='scheduleswim',
            name='SC_weekend_practices',
        ),
    ]
